spring:
  datasource:
    url: jdbc:oracle:thin:@10.1.3.62:1521:oradb
    username: east3
    password: east3
    hikari:
#      leakDetectionThreshold: 2000
      minimum-idle: 10
      maximum-pool-size: 200
      data-source-properties:
        oracle.jdbc.implicitStatementCacheSize: 32
#        oracle.jdbc.remarksReporting: false

logging:
#  file: validator.log
  level:
    com.zaxxer.hikari: debug

east:
  validator:
#    rules: file:rules.csv
#    cache-path: cache
#    cache-maximum-weight: 104857600
#    entity-parallelism: 1
#    validate-parallelism: 16
    output:
#    table-format: EAST_FILE_%s
#    extra-condition:
    cjrq-date: 20191031
#    org-id: 70
    table:
      - name: CKRDQSXQKB
        sql: select * from PM_EAST_CKRDQSXQKB
      - name: CKRFQYWQKB
        sql: select * from PM_EAST_CKRFQYWQKB
      - name: CKRJCQKB
        sql: select * from PM_EAST_CKRJCQKB
      - name: CZXX
        sql: select * from PM_EAST_CZXX
      - name: DBGX
        sql: select * from PM_EAST_DBGX
      - name: DGBWSXYW
        sql: select * from PM_EAST_DGBWSXYW
      - name: DGDQCKFHZ
        sql: select * from PM_EAST_DGDQCKFHZ
      - name: DGDQCKFHZMXJL
        sql: select * from PM_EAST_DGDQCKFHZMXJL
      - name: DGHQCKFHZ
        sql: select * from PM_EAST_DGHQCKFHZ
      - name: DGHQCKFHZMXJL
        sql: select * from PM_EAST_DGHQCKFHZMXJL
      - name: DGKH
        sql: select * from PM_EAST_DGKH
      - name: DGXDFHZ
        sql: select * from PM_EAST_DGXDFHZ
      - name: DGXDFHZMXJL
        sql: select * from PM_EAST_DGXDFHZMXJL
      - name: DGXDYWJJ
        sql: select * from PM_EAST_DGXDYWJJ
      - name: DKHX
        sql: select * from PM_EAST_DKHX
      - name: DKWJXTBD
        sql: select * from PM_EAST_DKWJXTBD
      - name: DKZQ
        sql: select * from PM_EAST_DKZQ
      - name: GDXX
        sql: select * from PM_EAST_GDXX
      - name: GLGX
        sql: select * from PM_EAST_GLGX
      - name: GRDQCKFHZ
        sql: select * from PM_EAST_GRDQCKFHZ
      - name: GRDQCKFHZMXJL
        sql: select * from PM_EAST_GRDQCKFHZMXJL
      - name: GRHQCKFHZ
        sql: select * from PM_EAST_GRHQCKFHZ
      - name: GRHQCKFHZMXJL
        sql: select * from PM_EAST_GRHQCKFHZMXJL
      - name: GRJCXX
        sql: select * from PM_EAST_GRJCXX
      - name: GRKHGXXX
        sql: select * from PM_EAST_GRKHGXXX
      - name: GRXDFHZ
        sql: select * from PM_EAST_GRXDFHZ
      - name: GRXDFHZMXJL
        sql: select * from PM_EAST_GRXDFHZMXJL
      - name: GRXDYWJJ
        sql: select * from PM_EAST_GRXDYWJJ
      - name: GWXXB
        sql: select * from PM_EAST_GWXXB
      - name: GYB
        sql: select * from PM_EAST_GYB
      - name: HLXXB
        sql: select * from PM_EAST_HLXXB
      - name: JGGXB
        sql: select * from PM_EAST_JGGXB
      - name: JGXXB
        sql: select * from PM_EAST_JGXXB
      - name: JJKXX
        sql: select * from PM_EAST_JJKXX
      - name: JRGJXXB
        sql: select * from PM_EAST_JRGJXXB
      - name: MYRZYWXXB
        sql: select * from PM_EAST_MYRZYWXXB
      - name: NBFHZ
        sql: select * from PM_EAST_NBFHZ
      - name: NBFHZMXJL
        sql: select * from PM_EAST_NBFHZMXJL
      - name: NBKMDZB
        sql: select * from PM_EAST_NBKMDZB
      - name: PJPMXXB
        sql: select * from PM_EAST_PJPMXXB
      - name: SXXX
        sql: select * from PM_EAST_SXXX
      - name: WTDK
        sql: select * from PM_EAST_WTDK
      - name: XDHTB
        sql: select * from PM_EAST_XDHTB
      - name: XDYWDBHT
        sql: select * from PM_EAST_XDYWDBHT
      - name: XDYWZHDYW
        sql: select * from PM_EAST_XDYWZHDYW
      - name: XDZCZR
        sql: select * from PM_EAST_XDZCZR
      - name: XMDKXXB
        sql: select * from PM_EAST_XMDKXXB
      - name: XYKXX
        sql: select * from PM_EAST_XYKXX
      - name: XYKZHJYMXB
        sql: select * from PM_EAST_XYKZHJYMXB
      - name: XYZHTB
        sql: select * from PM_EAST_XYZHTB
      - name: XYZMXB
        sql: select * from PM_EAST_XYZMXB
      - name: YGB
        sql: select * from PM_EAST_YGB
      - name: YTDK
        sql: select * from PM_EAST_YTDK
      - name: ZCFZKMTJB
        sql: select * from PM_EAST_ZCFZKMTJB
      - name: ZCZRGXB
        sql: select * from PM_EAST_ZCZRGXB
      - name: ZJJYXXB
        sql: select * from PM_EAST_ZJJYXXB
      - name: ZYZJJYXXB
        sql: select * from PM_EAST_ZYZJJYXXB
      - name: ZYZJYWYEB
        sql: select * from PM_EAST_ZYZJYWYEB

#      - name: CKRDQSXQKB
#      - name: CKRFQYWQKB
#      - name: CKRJCQKB
#      - name: CZXX
#      - name: DBGX
#      - name: DGBWSXYW
#      - name: DGDQCKFHZ
#      - name: DGDQCKFHZMXJL
#      - name: DGHQCKFHZ
#      - name: DGHQCKFHZMXJL
#      - name: DGKH
#      - name: DGXDFHZ
#      - name: DGXDFHZMXJL
#      - name: DGXDYWJJ
#      - name: DKHX
#      - name: DKWJXTBD
#      - name: DKZQ
#      - name: GDXX
#      - name: GLGX
#      - name: GRDQCKFHZ
#      - name: GRDQCKFHZMXJL
#      - name: GRHQCKFHZ
#      - name: GRHQCKFHZMXJL
#      - name: GRJCXX
#      - name: GRKHGXXX
#      - name: GRXDFHZ
#      - name: GRXDFHZMXJL
#      - name: GRXDYWJJ
#      - name: GWXXB
#      - name: GYB
#      - name: HLXXB
#      - name: JGGXB
#      - name: JGXXB
#      - name: JJKXX
#      - name: JRGJXXB
#      - name: MYRZYWXXB
#      - name: NBFHZ
#      - name: NBFHZMXJL
#      - name: NBKMDZB
#      - name: PJPMXXB
#      - name: SXXX
#      - name: WTDK
#      - name: XDHTB
#      - name: XDYWDBHT
#      - name: XDYWZHDYW
#      - name: XDZCZR
#      - name: XMDKXXB
#      - name: XYKXX
#      - name: XYKZHJYMXB
#      - name: XYZHTB
#      - name: XYZMXB
#      - name: YGB
#      - name: YTDK
#      - name: ZCFZKMTJB
#      - name: ZCZRGXB
#      - name: ZJJYXXB
#      - name: ZYZJJYXXB
#      - name: ZYZJYWYEB
#        sql: select * from PM_EAST_ZYZJYWYEB where CJRQ_DATE BETWEEN '20191000' AND '20191099' AND DATA_STATUS = '21'
